/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import g1_sistemahospitalario.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author fernandafajardo
 */
public class PantallaPaciente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPaciente
     */
    public PantallaPaciente() {
        initComponents();
        // Ocultar paneles al inicio
        panelDatosP.setVisible(false);
        panelCitas.setVisible(false);
        panelDiagnostico.setVisible(false);
        panelMedicamentos.setVisible(false);

        // Agregar ActionListener al cmbDatos
        cmbDatos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (cmbDatos.getSelectedItem() == null) {
                    System.out.println("Error: cmbDatos no tiene selección válida.");
                    return;
                }

                String seleccion = cmbDatos.getSelectedItem().toString();
                panelDatosP.setVisible(seleccion.equals("Datos Personales"));
                panelCitas.setVisible(seleccion.equals("Citas"));
                panelDiagnostico.setVisible(seleccion.equals("Diagnósticos"));
                panelMedicamentos.setVisible(seleccion.equals("Medicamentos"));
            }
        });
    }
    
    //Nombre del usuario mostrado en la pantallas
    public void setNombreUsuario(String nombre){
        txtNombreP.setText("Bienvenid@, " + nombre);
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreP = new javax.swing.JLabel();
        btnSalir = new javax.swing.JToggleButton();
        cmbDatos = new javax.swing.JComboBox<>();
        panelDatosP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContr = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnModificarD = new javax.swing.JButton();
        pDP = new javax.swing.JPanel();
        txtInfoDatos = new javax.swing.JLabel();
        panelCitas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNomC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbSelectM = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnReservar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        pC = new javax.swing.JPanel();
        txtInfoDatos2 = new javax.swing.JLabel();
        btnBuscarP = new javax.swing.JButton();
        panelDiagnostico = new javax.swing.JPanel();
        txtInfoDatos1 = new javax.swing.JLabel();
        panelMedicamentos = new javax.swing.JPanel();
        txtInfoDatos3 = new javax.swing.JLabel();
        bgP = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paciente");

        jPanel1.setMinimumSize(new java.awt.Dimension(372, 526));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreP.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        jPanel1.add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 250, -1));

        btnSalir.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 204, 204));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        cmbDatos.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        cmbDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Datos Personales", "Citas", "Diagnósticos", "Medicamentos" }));
        jPanel1.add(cmbDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        panelDatosP.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        jLabel1.setText("Nombre");

        txtNom.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        txtNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        jLabel2.setText("Teléfono");

        txtTel.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        txtTel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        jLabel3.setText("Correo");

        txtCorreo.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel4.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        jLabel4.setText("Contraseña");

        txtContr.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        txtContr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnBuscar.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 204, 204));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificarD.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        btnModificarD.setForeground(new java.awt.Color(0, 204, 204));
        btnModificarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnModificarD.setText("Modificar");
        btnModificarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDActionPerformed(evt);
            }
        });

        pDP.setBackground(new java.awt.Color(255, 255, 255));
        pDP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kodchasan", 0, 13), new java.awt.Color(0, 204, 204))); // NOI18N
        pDP.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        pDP.setPreferredSize(new java.awt.Dimension(372, 526));
        pDP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInfoDatos.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        pDP.add(txtInfoDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 100));

        javax.swing.GroupLayout panelDatosPLayout = new javax.swing.GroupLayout(panelDatosP);
        panelDatosP.setLayout(panelDatosPLayout);
        panelDatosPLayout.setHorizontalGroup(
            panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pDP, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelDatosPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelDatosPLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDatosPLayout.createSequentialGroup()
                            .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTel)
                                .addComponent(txtCorreo)))
                        .addGroup(panelDatosPLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtContr, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosPLayout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarD)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosPLayout.setVerticalGroup(
            panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContr, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(panelDatosPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnModificarD))
                .addGap(12, 12, 12)
                .addComponent(pDP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(panelDatosP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 250, 350));

        panelCitas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        jLabel6.setText("Paciente");

        txtNomC.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        txtNomC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel7.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        jLabel7.setText("Médico");

        cmbSelectM.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        cmbSelectM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--" }));
        cmbSelectM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectMActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        jLabel8.setText("Fecha");

        txtFecha.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnReservar.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        btnReservar.setForeground(new java.awt.Color(0, 204, 204));
        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 204, 204));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        pC.setBackground(new java.awt.Color(255, 255, 255));
        pC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)), "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kodchasan", 0, 13), new java.awt.Color(0, 204, 204))); // NOI18N
        pC.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        pC.setPreferredSize(new java.awt.Dimension(372, 526));
        pC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInfoDatos2.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        pC.add(txtInfoDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 100));

        btnBuscarP.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        btnBuscarP.setForeground(new java.awt.Color(0, 204, 204));
        btnBuscarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscarP.setText("Buscar");
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCitasLayout = new javax.swing.GroupLayout(panelCitas);
        panelCitas.setLayout(panelCitasLayout);
        panelCitasLayout.setHorizontalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCitasLayout.createSequentialGroup()
                .addComponent(pC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCitasLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCitasLayout.createSequentialGroup()
                        .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSelectM, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCitasLayout.createSequentialGroup()
                        .addComponent(btnReservar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarP))
                    .addGroup(panelCitasLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCitasLayout.setVerticalGroup(
            panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCitasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cmbSelectM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnBuscarP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addGap(12, 12, 12)
                .addComponent(pC, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(panelCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 250, 350));

        panelDiagnostico.setBackground(new java.awt.Color(255, 255, 255));
        panelDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)), "Diagnóstico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kodchasan", 0, 13), new java.awt.Color(0, 204, 204))); // NOI18N
        panelDiagnostico.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        panelDiagnostico.setPreferredSize(new java.awt.Dimension(372, 526));
        panelDiagnostico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInfoDatos1.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        panelDiagnostico.add(txtInfoDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 290));

        jPanel1.add(panelDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, 340));

        panelMedicamentos.setBackground(new java.awt.Color(255, 255, 255));
        panelMedicamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)), "Medicamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kodchasan", 0, 13), new java.awt.Color(0, 204, 204))); // NOI18N
        panelMedicamentos.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        panelMedicamentos.setPreferredSize(new java.awt.Dimension(372, 526));
        panelMedicamentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInfoDatos3.setFont(new java.awt.Font("Kodchasan", 0, 13)); // NOI18N
        panelMedicamentos.add(txtInfoDatos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 290));

        jPanel1.add(panelMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, 340));

        bgP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg2.jpg"))); // NOI18N
        bgP.setText("background");
        jPanel1.add(bgP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 372, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarDActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbSelectMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectMActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgP;
    public javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarP;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnModificarD;
    public javax.swing.JButton btnReservar;
    public javax.swing.JToggleButton btnSalir;
    public javax.swing.JComboBox<String> cmbDatos;
    public javax.swing.JComboBox<String> cmbSelectM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel pC;
    public javax.swing.JPanel pDP;
    public javax.swing.JPanel panelCitas;
    public javax.swing.JPanel panelDatosP;
    public javax.swing.JPanel panelDiagnostico;
    public javax.swing.JPanel panelMedicamentos;
    public javax.swing.JTextField txtContr;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtFecha;
    private javax.swing.JLabel txtInfoDatos;
    private javax.swing.JLabel txtInfoDatos1;
    private javax.swing.JLabel txtInfoDatos2;
    private javax.swing.JLabel txtInfoDatos3;
    public javax.swing.JTextField txtNom;
    public javax.swing.JTextField txtNomC;
    public static javax.swing.JLabel txtNombreP;
    public javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
